name: Deploy to Windows VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_windows.txt
        pip install pywin32

    - name: Create deployment package
      run: |
        # Create package directory
        New-Item -ItemType Directory -Force -Path .\deploy
        
        # Copy required files
        Copy-Item api.py .\deploy\
        Copy-Item best_model_RandomForestRegressor.pkl .\deploy\
        Copy-Item web.config .\deploy\
        Copy-Item requirements_windows.txt .\deploy\
        Copy-Item app_win_service.py .\deploy\
        
        # Create startup script
        $startupScript = @'
        @echo off
        cd /d "%~dp0"
        python -m waitress --port=5000 api:app
        '@
        $startupScript | Out-File -FilePath .\deploy\start_web.bat -Encoding ascii

        # Create installation script
        $installScript = @'
        # Create necessary directories
        New-Item -ItemType Directory -Force -Path C:\logs
        
        # Install Python if not exists
        if (-not (Test-Path "C:\Python39\python.exe")) {
            Write-Host "Installing Python..."
            Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.9.13/python-3.9.13-amd64.exe" -OutFile "python-installer.exe"
            Start-Process -FilePath ".\python-installer.exe" -ArgumentList "/quiet InstallAllUsers=1 PrependPath=1" -Wait
            Remove-Item "python-installer.exe"
        }
        
        # Install required packages
        & C:\Python39\python.exe -m pip install --upgrade pip
        & C:\Python39\python.exe -m pip install -r C:\inetpub\wwwroot\CarPricePrediction\requirements_windows.txt
        & C:\Python39\python.exe -m pip install waitress pywin32
        
        # Configure IIS
        Import-Module WebAdministration
        
        # Create or update the website
        $iisApp = Get-IISSite -Name "CarPricePrediction" -ErrorAction SilentlyContinue
        
        if (-not $iisApp) {
            New-IISSite -Name "CarPricePrediction" `
                       -PhysicalPath "C:\inetpub\wwwroot\CarPricePrediction" `
                       -BindingInformation "*:80:" `
                       -Force
        } else {
            Set-ItemProperty -Path "IIS:\Sites\CarPricePrediction" -Name physicalPath -Value "C:\inetpub\wwwroot\CarPricePrediction"
        }
        
        # Set permissions
        $acl = Get-Acl "C:\inetpub\wwwroot\CarPricePrediction"
        $accessRule = New-Object System.Security.AccessControl.FileSystemAccessRule("IIS AppPool\DefaultAppPool", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow")
        $acl.SetAccessRule($accessRule)
        Set-Acl "C:\inetpub\wwwroot\CarPricePrediction" $acl
        
        # Restart IIS
        iisreset
        
        Write-Host "Installation completed successfully!"
        Write-Host "To start the application, run: start_web.bat"
        '@
        $installScript | Out-File -FilePath .\deploy\install.ps1 -Encoding ascii

    - name: Upload deployment package
      uses: actions/upload-artifact@v4
      with:
        name: deploy-package
        path: deploy/
        retention-days: 1

    - name: Deploy to Windows VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: 22
        source: "deploy/*"
        target: "C:\\inetpub\\wwwroot\\CarPricePrediction\\"

    - name: Install and configure on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: 22
        script: |
          # Run installation script
          cd C:\inetpub\wwwroot\CarPricePrediction
          powershell -ExecutionPolicy Bypass -File .\install.ps1
          
          # Start the web application
          Start-Process -FilePath "cmd.exe" -ArgumentList "/c start_web.bat" -WindowStyle Hidden
          Start-Service -Name $serviceName
          
          # Restart IIS
          iisreset
